### ISSUE TITLE
Chat Stream

### ISSUE THREAD

**Issue by micahlt** [MicahIncorporated/cameroncollab#1]
Here’s where we’ll chat, Cameron. 👌🏻

**Comment by micahlt** [comment]
Okay.  Here’s a basic guide to HTML I just made:

`<html> and </html>`
Always used as the beginning and ending of a document.  

`<head> and </head>`
The header which contains the site name, description, and other metadata.

`<body> and </body>` 
Defines the body, or visual section of a webpage.

`<h#> and </h#>`
Replace # with a number, and it defines a header text.  The smaller the number, the bigger the text.  No negative numbers.

`<p> and </p>` 
Paragraph.  Defines the normal paragraph styling.

`<br>` 
Creates a page break

`<style>` 
Embeds CSS styling into a page.

`<a href = “link.com”>Link</a>`
Syntax for a visual link.  Can be in a `<p>` element or a `<h#>` element.

**Comment by MagnetiteDragon** [comment]
Wow thanks dude.

**Comment by micahlt** [comment]
So, this is easier, right?

**Comment by micahlt** [comment]
I also added you to another place on GitHub: 
https://github.com/orgs/MicahIncorporated/teams/cameronsite

**Comment by micahlt** [comment]
Honestly, let’s just move to there.  It’s better.
